# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class KubieGo < Formula
  desc "Kubernetes context and namespace manager written in Go"
  homepage "https://github.com/stanislavtrubachev/kubie-go"
  version "0.1.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/stanislavtrubachev/kubie-go/releases/download/v0.1.2/kubie-go_0.1.2_darwin_amd64.tar.gz"
      sha256 "c26160a1edc174ab42b94d41e5e25aa4355269715b63e784928614be223b62be"

      define_method(:install) do
        bin.install "kubie-go"
        bin.install_symlink bin/"kubie-go" => "kubie"
        zsh_completion.install "completion/kubie.zsh" => "_kubie"
        bash_completion.install "completion/kubie.bash"
        fish_completion.install "completion/kubie.fish"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/stanislavtrubachev/kubie-go/releases/download/v0.1.2/kubie-go_0.1.2_darwin_arm64.tar.gz"
      sha256 "39d133f57dbc8a0dd46f806648d734590867d3a6ef3c503edf30ced1645df41d"

      define_method(:install) do
        bin.install "kubie-go"
        bin.install_symlink bin/"kubie-go" => "kubie"
        zsh_completion.install "completion/kubie.zsh" => "_kubie"
        bash_completion.install "completion/kubie.bash"
        fish_completion.install "completion/kubie.fish"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/stanislavtrubachev/kubie-go/releases/download/v0.1.2/kubie-go_0.1.2_linux_amd64.tar.gz"
      sha256 "81b6180ae3e7f8b8803dfd2e5cebf11ea75f4ff8838b0cd2fe579fc58ab3afcf"
      define_method(:install) do
        bin.install "kubie-go"
        bin.install_symlink bin/"kubie-go" => "kubie"
        zsh_completion.install "completion/kubie.zsh" => "_kubie"
        bash_completion.install "completion/kubie.bash"
        fish_completion.install "completion/kubie.fish"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/stanislavtrubachev/kubie-go/releases/download/v0.1.2/kubie-go_0.1.2_linux_arm64.tar.gz"
      sha256 "5368d48b069a2c79ce97e4ae90f5a57cd148ee22e6598f1a9f464d54592ebf2a"
      define_method(:install) do
        bin.install "kubie-go"
        bin.install_symlink bin/"kubie-go" => "kubie"
        zsh_completion.install "completion/kubie.zsh" => "_kubie"
        bash_completion.install "completion/kubie.bash"
        fish_completion.install "completion/kubie.fish"
      end
    end
  end

  test do
    assert_match "Usage", shell_output("#{bin}/kubie-go 2>&1", 1)
  end
end
