# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class KubieGo < Formula
  desc "Kubernetes context and namespace manager written in Go"
  homepage "https://github.com/stanislavtrubachev/kubie-go"
  version "0.1.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/stanislavtrubachev/kubie-go/releases/download/v0.1.1/kubie-go_0.1.1_darwin_amd64.tar.gz"
      sha256 "230bbed7be6e54f2d15f74d2c812866642b7a848edda4dda8dcfd6a4277e1988"

      define_method(:install) do
        bin.install "kubie-go"
        bin.install_symlink bin/"kubie-go" => "kubie"
        zsh_completion.install "completion/kubie.zsh" => "_kubie"
        bash_completion.install "completion/kubie.bash"
        fish_completion.install "completion/kubie.fish"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/stanislavtrubachev/kubie-go/releases/download/v0.1.1/kubie-go_0.1.1_darwin_arm64.tar.gz"
      sha256 "568b04abd41cb682374fcf13b366066ba0ed8171af370957c54642bb77f780d3"

      define_method(:install) do
        bin.install "kubie-go"
        bin.install_symlink bin/"kubie-go" => "kubie"
        zsh_completion.install "completion/kubie.zsh" => "_kubie"
        bash_completion.install "completion/kubie.bash"
        fish_completion.install "completion/kubie.fish"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/stanislavtrubachev/kubie-go/releases/download/v0.1.1/kubie-go_0.1.1_linux_amd64.tar.gz"
      sha256 "58bcf81425739b1d25a480fcb97c8d25856f289ee71bcf86792b4a90a3f1c611"
      define_method(:install) do
        bin.install "kubie-go"
        bin.install_symlink bin/"kubie-go" => "kubie"
        zsh_completion.install "completion/kubie.zsh" => "_kubie"
        bash_completion.install "completion/kubie.bash"
        fish_completion.install "completion/kubie.fish"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/stanislavtrubachev/kubie-go/releases/download/v0.1.1/kubie-go_0.1.1_linux_arm64.tar.gz"
      sha256 "7a00f93beac227d3b30b2bd272025cd3c62b9009220440d919bac435df697ba5"
      define_method(:install) do
        bin.install "kubie-go"
        bin.install_symlink bin/"kubie-go" => "kubie"
        zsh_completion.install "completion/kubie.zsh" => "_kubie"
        bash_completion.install "completion/kubie.bash"
        fish_completion.install "completion/kubie.fish"
      end
    end
  end

  test do
    assert_match "Usage", shell_output("#{bin}/kubie-go 2>&1", 1)
  end
end
