# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class KubieGo < Formula
  desc "Kubernetes context and namespace manager written in Go."
  homepage "https://github.com/stanislavtrubachev/kubie-go"
  version "0.1.3"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/stanislavtrubachev/kubie-go/releases/download/v0.1.3/kubie-go_0.1.3_darwin_amd64.tar.gz"
      sha256 "25654e0897d50b0cb34230734b0f60c69b168e522c61d2f31cca884e9f0eb0be"

      define_method(:install) do
        bin.install "kubie-go"
        bin.install_symlink bin/"kubie-go" => "kubie"
        zsh_completion.install "completion/kubie.zsh" => "_kubie"
        bash_completion.install "completion/kubie.bash"
        fish_completion.install "completion/kubie.fish"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/stanislavtrubachev/kubie-go/releases/download/v0.1.3/kubie-go_0.1.3_darwin_arm64.tar.gz"
      sha256 "f95346c949d38e1ed780008eb0a1ced163bb81b62b2ac89801692f6f88db67c9"

      define_method(:install) do
        bin.install "kubie-go"
        bin.install_symlink bin/"kubie-go" => "kubie"
        zsh_completion.install "completion/kubie.zsh" => "_kubie"
        bash_completion.install "completion/kubie.bash"
        fish_completion.install "completion/kubie.fish"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/stanislavtrubachev/kubie-go/releases/download/v0.1.3/kubie-go_0.1.3_linux_amd64.tar.gz"
      sha256 "cdf546687c7172d056383b2112dd6e95e7c87a04617181ca42131198302148f1"
      define_method(:install) do
        bin.install "kubie-go"
        bin.install_symlink bin/"kubie-go" => "kubie"
        zsh_completion.install "completion/kubie.zsh" => "_kubie"
        bash_completion.install "completion/kubie.bash"
        fish_completion.install "completion/kubie.fish"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/stanislavtrubachev/kubie-go/releases/download/v0.1.3/kubie-go_0.1.3_linux_arm64.tar.gz"
      sha256 "f29c395766cba484898aebe25e153195b40d3bc5b4e5a4d5284c35bf2e6384f6"
      define_method(:install) do
        bin.install "kubie-go"
        bin.install_symlink bin/"kubie-go" => "kubie"
        zsh_completion.install "completion/kubie.zsh" => "_kubie"
        bash_completion.install "completion/kubie.bash"
        fish_completion.install "completion/kubie.fish"
      end
    end
  end

  test do
    assert_match "Usage", shell_output("#{bin}/kubie-go 2>&1", 1)
  end
end
