# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class KubieGo < Formula
  desc "Kubernetes context and namespace manager written in Go."
  homepage "https://github.com/stanislavtrubachev/kubie-go"
  version "0.1.3"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/stanislavtrubachev/kubie-go/releases/download/v0.1.3/kubie-go_0.1.3_darwin_amd64.tar.gz"
      sha256 "bcd68f178eeabc370db946a8135870f641bd677f5e3300eee950a45f6f3781fd"

      define_method(:install) do
        bin.install "kubie-go"
        bin.install_symlink bin/"kubie-go" => "kubie"
        zsh_completion.install "completion/kubie.zsh" => "_kubie"
        bash_completion.install "completion/kubie.bash"
        fish_completion.install "completion/kubie.fish"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/stanislavtrubachev/kubie-go/releases/download/v0.1.3/kubie-go_0.1.3_darwin_arm64.tar.gz"
      sha256 "2fb5d8d3509f5c0408c0207960821a2d86d8459da9651eecd1e2a24b9b1140c9"

      define_method(:install) do
        bin.install "kubie-go"
        bin.install_symlink bin/"kubie-go" => "kubie"
        zsh_completion.install "completion/kubie.zsh" => "_kubie"
        bash_completion.install "completion/kubie.bash"
        fish_completion.install "completion/kubie.fish"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/stanislavtrubachev/kubie-go/releases/download/v0.1.3/kubie-go_0.1.3_linux_amd64.tar.gz"
      sha256 "d040a67823ea70dfcb5463ee85135a410854f18e88173c17e9a43f48b44905cd"
      define_method(:install) do
        bin.install "kubie-go"
        bin.install_symlink bin/"kubie-go" => "kubie"
        zsh_completion.install "completion/kubie.zsh" => "_kubie"
        bash_completion.install "completion/kubie.bash"
        fish_completion.install "completion/kubie.fish"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/stanislavtrubachev/kubie-go/releases/download/v0.1.3/kubie-go_0.1.3_linux_arm64.tar.gz"
      sha256 "25d4eadfd7611091504d7b966436c28ca6c2b1838473b5cfca7cfecd6fc4e940"
      define_method(:install) do
        bin.install "kubie-go"
        bin.install_symlink bin/"kubie-go" => "kubie"
        zsh_completion.install "completion/kubie.zsh" => "_kubie"
        bash_completion.install "completion/kubie.bash"
        fish_completion.install "completion/kubie.fish"
      end
    end
  end

  test do
    assert_match "Usage", shell_output("#{bin}/kubie-go 2>&1", 1)
  end
end
